### ISSUE TITLE
按照.travis.yml 文件编译pdf报undefined local variable or method `latex' for main:Object (NameError)错误

### ISSUE THREAD

**Issue by wming126** [RT-Thread/rtthread-manual-doc#125]
请教下,我按照按照.travis.yml 文件安装依赖软件包后,编译pdf仍然无法编译通过,我使用的系统是Ubuntu16.04.3 
```
RC530-RC730:~/rtthread-manual-doc$ ./makepdfs 

Will generate pdf for the following languages:
	 epub mkbok Rakefile README.md stylesheets template.html title.zh.txt zh

The generation process will start now.
epub:
	Parsing preface markdown... done
	Parsing main chapters markdown... done
	Parsing appendix markdown... done
	Creating main.tex for epub... (erb):220:in `block (3 levels) in <main>': undefined local variable or method `latex' for main:Object (NameError)
	from /usr/lib/ruby/2.3.0/erb.rb:864:in `eval'
	from /usr/lib/ruby/2.3.0/erb.rb:864:in `result'
	from ./latex/makepdf:202:in `block (3 levels) in <main>'
	from ./latex/makepdf:201:in `open'
	from ./latex/makepdf:201:in `block (2 levels) in <main>'
	from ./latex/makepdf:157:in `each'
	from ./latex/makepdf:157:in `block in <main>'
	from ./latex/makepdf:19:in `figures'
	from ./latex/makepdf:156:in `<main>'
```

**Comment by BernardXiong** [comment]
是否是版本的缘故？

**Comment by wming126** [comment]
我感觉也是，没有找到原因呢。

**Comment by z14git** [comment]
按照.travis.yml 文件编译的话，根本就不需要用到./makepdfs 这个命令
